/**
 * test_cuda.cpp — CUDA heightmap: correctness against the C reference + benchmark.
 *
 * Test 1 (génération) : a 100x100 heightmap is generated by the CPU C code
 *                       (generate_column_from_y) and by CUDA. Every one of the
 *                       10 000 heights must match exactly.
 * Test 2 (temps)      : same workload, timed. Reports the speedup and splits
 *                       the GPU time into CPU biome prep / upload / kernels.
 *
 * Build: make -C cuda test_cuda
 * Run:   cuda/test_cuda.exe [seed] [x0] [z0] [size] [repeats]
 */

#include "village_noise_host.hpp"

extern "C" {
    #include "noise.h"
    #include "biomenoise.h"
    #include "generator.h"
}

#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstring>
#include <chrono>
#include <string>
#include <vector>

using Clock = std::chrono::high_resolution_clock;
static double msSince(Clock::time_point t0) {
    return std::chrono::duration<double, std::milli>(Clock::now() - t0).count();
}

static int notAirPredicate(Block block, void*) { return block != BLOCK_AIR; }
static int stonePredicate (Block block, void*) { return block == BLOCK_STONE; }

// Reference heightmap, straight through the existing C path.
// The noise-column cache is dropped first so the timing covers a cold zone.
static double cpuHeightmap(SurfaceGen* sg, int x0, int z0, int w, int h,
                           BlockPredicate pred, std::vector<int>& out)
{
    free_surface_cache(sg);
    out.resize((size_t)w * h);

    auto t0 = Clock::now();
    for (int iz = 0; iz < h; iz++)
        for (int ix = 0; ix < w; ix++)
            out[(size_t)iz * w + ix] =
                generate_column_from_y(sg, x0 + ix, z0 + iz, pred, sg);
    return msSince(t0);
}

static int compare(const std::vector<int>& cpu, const std::vector<int>& gpu,
                   int x0, int z0, int w, const char* label)
{
    int mismatches = 0;
    for (size_t i = 0; i < cpu.size(); i++) {
        if (cpu[i] == gpu[i]) continue;
        if (mismatches < 10) {
            printf("  MISMATCH %s at (%d, %d): CPU=%d  GPU=%d\n", label,
                   x0 + (int)(i % w), z0 + (int)(i / w), cpu[i], gpu[i]);
        }
        mismatches++;
    }
    return mismatches;
}

int main(int argc, char** argv)
{
    uint64_t seed = 123456789ULL;
    int x0 = 0, z0 = 0, size = 100, repeats = 5;
    if (argc > 1) seed    = strtoull(argv[1], nullptr, 10);
    if (argc > 2) x0      = atoi(argv[2]);
    if (argc > 3) z0      = atoi(argv[3]);
    if (argc > 4) size    = atoi(argv[4]);
    if (argc > 5) repeats = atoi(argv[5]);

    const int w = size, h = size;
    const int numQueries = w * h;

    printf("=== CUDA heightmap test ===\n");
    printf("seed=%llu  zone=(%d,%d) %dx%d  repeats=%d\n\n",
           (unsigned long long)seed, x0, z0, w, h, repeats);

    CubiomesContext ctx;
    init_cubiomes_context(&ctx, MC_1_16_1, seed);

    SurfaceGen sg;
    memset(&sg, 0, sizeof(sg));
    setup_surface_gen_with_cubiomes(&sg, &ctx);
    printf("SurfaceGen: chunk %dx%d, startSizeY=%d, noiseSizeY=%d, seaLevel=%d\n\n",
           sg.chunkWidth, sg.chunkHeight, sg.startSizeY, sg.noiseSizeY, sg.seaLevel);

    CudaHeightBatcher batcher(&ctx, &sg);
    if (!batcher.isValid()) {
        fprintf(stderr, "CUDA init failed\n");
        free_surface_cache(&sg);
        free_cubiomes_context_cache(&ctx);
        return 1;
    }

    int totalMismatches = 0;

    // ------------------------------------------------------------------
    // Test 1 — génération : CPU vs GPU, both predicates
    // ------------------------------------------------------------------
    printf("--- Test 1 : génération (%d hauteurs) ---\n", numQueries);

    std::vector<int> cpuNotAir, gpuNotAir(numQueries);
    std::vector<int> cpuStone,  gpuStone(numQueries);

    cpuHeightmap(&sg, x0, z0, w, h, notAirPredicate, cpuNotAir);
    if (batcher.heightmap(x0, z0, w, h, HEIGHT_PRED_NOT_AIR, gpuNotAir.data()) != 0) {
        fprintf(stderr, "cuda heightmap (NOT_AIR) failed\n");
        return 1;
    }
    int mmA = compare(cpuNotAir, gpuNotAir, x0, z0, w, "[NOT_AIR]");
    printf("  prédicat NOT_AIR (première surface) : %s (%d écarts)\n",
           mmA == 0 ? "OK" : "ECHEC", mmA);

    cpuHeightmap(&sg, x0, z0, w, h, stonePredicate, cpuStone);
    if (batcher.heightmap(x0, z0, w, h, HEIGHT_PRED_STONE, gpuStone.data()) != 0) {
        fprintf(stderr, "cuda heightmap (STONE) failed\n");
        return 1;
    }
    int mmB = compare(cpuStone, gpuStone, x0, z0, w, "[STONE]");
    printf("  prédicat STONE (WORLD_SURFACE_WG)   : %s (%d écarts)\n",
           mmB == 0 ? "OK" : "ECHEC", mmB);
    totalMismatches += mmA + mmB;

    // Sanity print: a few sampled heights
    printf("  échantillon :");
    for (int i = 0; i < 5; i++) {
        int ix = (i * (w - 1)) / 4, iz = (i * (h - 1)) / 4;
        printf("  (%d,%d)=%d", x0 + ix, z0 + iz, gpuNotAir[(size_t)iz * w + ix]);
    }
    printf("\n\n");

    // ------------------------------------------------------------------
    // Test 1b — chemin "requêtes dispersées" (utilisé par le générateur de villages)
    // ------------------------------------------------------------------
    printf("--- Test 1b : requêtes dispersées ---\n");
    {
        const int n = 2000;
        std::vector<int> qx(n), qz(n);
        srand(1234);
        for (int i = 0; i < n; i++) {
            qx[i] = x0 + (rand() % 4096) - 2048;
            qz[i] = z0 + (rand() % 4096) - 2048;
        }

        batcher.reset();
        for (int i = 0; i < n; i++) batcher.addQuery(qx[i], qz[i]);
        if (batcher.execute(HEIGHT_PRED_STONE) != 0) {
            fprintf(stderr, "cuda scattered batch failed\n");
            return 1;
        }

        free_surface_cache(&sg);
        int mm = 0;
        for (int i = 0; i < n; i++) {
            int cpu = generate_column_from_y(&sg, qx[i], qz[i], stonePredicate, &sg);
            int gpu = batcher.getHeight(i);
            if (cpu != gpu) {
                if (mm < 10) printf("  MISMATCH at (%d, %d): CPU=%d  GPU=%d\n",
                                    qx[i], qz[i], cpu, gpu);
                mm++;
            }
        }
        printf("  %d points dispersés (%d colonnes) : %s (%d écarts)\n\n",
               n, batcher.lastColumnCount(), mm == 0 ? "OK" : "ECHEC", mm);
        totalMismatches += mm;
    }

    // ------------------------------------------------------------------
    // Test 1c — startSizeY modifié en cours de route (SurfaceGenWrapper le fait)
    // ------------------------------------------------------------------
    printf("--- Test 1c : startSizeY modifié après construction ---\n");
    {
        const int saved = sg.startSizeY;
        sg.startSizeY = 20;
        free_surface_cache(&sg);       // le cache CPU dépend de startSizeY

        std::vector<int> cpuBuf, gpuBuf((size_t)50 * 50);
        cpuHeightmap(&sg, x0, z0, 50, 50, notAirPredicate, cpuBuf);
        int rc = batcher.heightmap(x0, z0, 50, 50, HEIGHT_PRED_NOT_AIR, gpuBuf.data());
        int mm = (rc == 0) ? compare(cpuBuf, gpuBuf, x0, z0, 50, "[startSizeY=20]") : 2500;
        printf("  startSizeY 12 -> 20 : %s (%d écarts)\n\n",
               mm == 0 ? "OK" : "ECHEC", mm);
        totalMismatches += mm;

        sg.startSizeY = saved;
        free_surface_cache(&sg);
    }

    // ------------------------------------------------------------------
    // Test 2 — temps de calcul
    // ------------------------------------------------------------------
    printf("--- Test 2 : temps de calcul (%dx%d, %d répétitions) ---\n", w, h, repeats);

    double cpuBest = 1e30, cpuTotal = 0.0;
    double gpuBest = 1e30, gpuTotal = 0.0;
    double prepBest = 0.0;
    float  msUp = 0, msCols = 0, msHts = 0, msDown = 0;

    std::vector<int> scratch(numQueries);
    for (int r = 0; r < repeats; r++) {
        // Each repeat uses a different zone so neither side benefits from a
        // warm cache — this is the "generate a fresh 100x100 zone" workload.
        int rx = x0 + r * 4096;
        int rz = z0 + r * 4096;

        double cpuMs = cpuHeightmap(&sg, rx, rz, w, h, notAirPredicate, cpuNotAir);
        cpuTotal += cpuMs;
        if (cpuMs < cpuBest) cpuBest = cpuMs;

        auto t0 = Clock::now();
        batcher.heightmap(rx, rz, w, h, HEIGHT_PRED_NOT_AIR, scratch.data());
        double gpuMs = msSince(t0);
        gpuTotal += gpuMs;
        if (gpuMs < gpuBest) {
            gpuBest  = gpuMs;
            prepBest = batcher.lastColumnPrepMs();
            batcher.lastGpuTimings(&msUp, &msCols, &msHts, &msDown);
        }

        totalMismatches += compare(cpuNotAir, scratch, rx, rz, w, "[bench]");
    }

    printf("  CPU  (C, generate_column_from_y) : %8.2f ms  (moy %.2f ms)  %.2f us/point\n",
           cpuBest, cpuTotal / repeats, cpuBest * 1000.0 / numQueries);
    printf("  GPU  (CUDA, bout en bout)        : %8.2f ms  (moy %.2f ms)  %.2f us/point\n",
           gpuBest, gpuTotal / repeats, gpuBest * 1000.0 / numQueries);
    printf("     préparation CPU (biomes)      : %8.2f ms\n", prepBest);
    printf("     upload / noise / heights / dl : %6.3f / %6.3f / %6.3f / %6.3f ms\n",
           msUp, msCols, msHts, msDown);
    printf("  Speedup total                    : %8.1fx\n", cpuBest / gpuBest);
    if (gpuBest - prepBest > 0.0)
        printf("  Speedup hors préparation biomes  : %8.1fx\n",
               cpuBest / (gpuBest - prepBest));

    // What the GPU path avoids doing on the CPU, for reference.
    {
        const int cw = sg.chunkWidth;
        int cx0 = (int)std::floor((double)x0 / cw), cz0 = (int)std::floor((double)z0 / cw);
        int gw = (int)std::floor((double)(x0 + w - 1) / cw) - cx0 + 2;
        int gh = (int)std::floor((double)(z0 + h - 1) / cw) - cz0 + 2;
        std::vector<double> d((size_t)gw * gh), s((size_t)gw * gh);

        auto tb = Clock::now();
        cubiomes_get_depth_and_scale_grid(&ctx, cx0, cz0, gw, gh, d.data(), s.data());
        double biomeMs = msSince(tb);

        auto tn = Clock::now();
        volatile double acc = 0.0;
        for (int cz = 0; cz < gh; cz++)
            for (int cx = 0; cx < gw; cx++)
                acc += cubiomes_noise_2d(cx0 + cx, cz0 + cz, &ctx);
        double roMs = msSince(tn);

        printf("     (pour info, sur CPU : depth/scale groupé %.2f ms, "
               "randomOffset %.2f ms — ce dernier est fait sur GPU) — %d colonnes\n",
               biomeMs, roMs, gw * gh);
    }

    // ------------------------------------------------------------------
    // Test 2b — passage à l'échelle : le GPU se remplit sur de grandes zones
    // ------------------------------------------------------------------
    printf("\n--- Test 2b : passage à l'échelle ---\n");
    printf("  %-10s %12s %12s %10s\n", "zone", "CPU (ms)", "GPU (ms)", "speedup");
    const int sizes[] = {100, 200, 400};
    for (int s : sizes) {
        std::vector<int> cpuBuf, gpuBuf((size_t)s * s);
        double cpuMs = cpuHeightmap(&sg, x0, z0, s, s, notAirPredicate, cpuBuf);

        auto t0 = Clock::now();
        int rc = batcher.heightmap(x0, z0, s, s, HEIGHT_PRED_NOT_AIR, gpuBuf.data());
        double gpuMs = msSince(t0);
        if (rc != 0) { printf("  %dx%d : ECHEC\n", s, s); continue; }

        int mm = compare(cpuBuf, gpuBuf, x0, z0, s, "[scale]");
        totalMismatches += mm;
        printf("  %-10s %12.2f %12.2f %9.1fx%s\n",
               (std::to_string(s) + "x" + std::to_string(s)).c_str(),
               cpuMs, gpuMs, cpuMs / gpuMs, mm ? "  (ECARTS!)" : "");
    }

    // ------------------------------------------------------------------
    printf("\n=== Résultat ===\n");
    if (totalMismatches == 0)
        printf("SUCCES : toutes les hauteurs CUDA sont identiques au C.\n");
    else
        printf("ECHEC : %d écarts au total.\n", totalMismatches);

    free_surface_cache(&sg);
    free_cubiomes_context_cache(&ctx);
    return totalMismatches == 0 ? 0 : 1;
}
