#include "village_structure_size.hpp" 
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>


typedef struct {
    const char *key;
    BPos value;
} Entry;
static const Entry STRUCTURE_SIZE[] = {
    { "common/iron_golem", { 1,3,1 } },
    { "common/well_bottom", { 4,3,4 } },
    { "common/animals/cat_black", { 1,3,1 } },
    { "common/animals/cat_british", { 1,3,1 } },
    { "common/animals/cat_calico", { 1,3,1 } },
    { "common/animals/cat_jellie", { 1,3,1 } },
    { "common/animals/cat_persian", { 1,3,1 } },
    { "common/animals/cat_ragdoll", { 1,3,1 } },
    { "common/animals/cat_red", { 1,3,1 } },
    { "common/animals/cat_siamese", { 1,3,1 } },
    { "common/animals/cat_tabby", { 1,3,1 } },
    { "common/animals/cat_white", { 1,3,1 } },
    { "common/animals/cows_1", { 1,3,1 } },
    { "common/animals/horses_1", { 1,3,1 } },
    { "common/animals/horses_2", { 1,3,1 } },
    { "common/animals/horses_3", { 1,3,1 } },
    { "common/animals/horses_4", { 1,3,1 } },
    { "common/animals/horses_5", { 1,3,1 } },
    { "common/animals/pigs_1", { 1,3,1 } },
    { "common/animals/sheep_1", { 1,3,1 } },
    { "common/animals/sheep_2", { 1,3,1 } },
    { "decays/grass_11x13", { 13,1,11 } },
    { "decays/grass_16x16", { 16,1,16 } },
    { "decays/grass_9x9", { 9,1,9 } },
    { "desert/desert_lamp_1", { 1,4,1 } },
    { "desert/houses/desert_animal_pen_1", { 10,6,7 } },
    { "desert/houses/desert_animal_pen_2", { 10,6,8 } },
    { "desert/houses/desert_armorer_1", { 7,7,7 } },
    { "desert/houses/desert_butcher_shop_1", { 8,5,8 } },
    { "desert/houses/desert_cartographer_house_1", { 7,7,7 } },
    { "desert/houses/desert_farm_1", { 5,6,7 } },
    { "desert/houses/desert_farm_2", { 7,7,10 } },
    { "desert/houses/desert_fisher_1", { 8,6,11 } },
    { "desert/houses/desert_fletcher_house_1", { 6,12,12 } },
    { "desert/houses/desert_large_farm_1", { 11,7,13 } },
    { "desert/houses/desert_library_1", { 9,7,5 } },
    { "desert/houses/desert_mason_1", { 7,5,8 } },
    { "desert/houses/desert_medium_house_1", { 6,6,7 } },
    { "desert/houses/desert_medium_house_2", { 11,9,7 } },
    { "desert/houses/desert_shepherd_house_1", { 11,6,5 } },
    { "desert/houses/desert_small_house_1", { 6,6,5 } },
    { "desert/houses/desert_small_house_2", { 7,6,5 } },
    { "desert/houses/desert_small_house_3", { 5,5,6 } },
    { "desert/houses/desert_small_house_4", { 5,5,5 } },
    { "desert/houses/desert_small_house_5", { 5,6,6 } },
    { "desert/houses/desert_small_house_6", { 6,18,5 } },
    { "desert/houses/desert_small_house_7", { 8,5,7 } },
    { "desert/houses/desert_small_house_8", { 5,5,5 } },
    { "desert/houses/desert_tannery_1", { 7,10,6 } },
    { "desert/houses/desert_temple_1", { 11,7,10 } },
    { "desert/houses/desert_temple_2", { 10,6,12 } },
    { "desert/houses/desert_tool_smith_1", { 9,9,9 } },
    { "desert/houses/desert_weaponsmith_1", { 10,6,7 } },
    { "desert/streets/corner_01", { 7,2,15 } },
    { "desert/streets/corner_02", { 6,2,6 } },
    { "desert/streets/crossroad_01", { 18,2,15 } },
    { "desert/streets/crossroad_02", { 11,2,11 } },
    { "desert/streets/crossroad_03", { 5,2,5 } },
    { "desert/streets/square_01", { 13,2,28 } },
    { "desert/streets/square_02", { 16,2,19 } },
    { "desert/streets/straight_01", { 15,2,12 } },
    { "desert/streets/straight_02", { 15,2,18 } },
    { "desert/streets/straight_03", { 4,2,3 } },
    { "desert/streets/turn_01", { 4,2,4 } },
    { "desert/terminators/terminator_01", { 3,2,3 } },
    { "desert/terminators/terminator_02", { 3,2,3 } },
    { "desert/town_centers/desert_meeting_point_1", { 17,6,9 } },
    { "desert/town_centers/desert_meeting_point_2", { 12,6,12 } },
    { "desert/town_centers/desert_meeting_point_3", { 15,6,15 } },
    { "desert/villagers/baby", { 1,2,1 } },
    { "desert/villagers/nitwit", { 1,3,1 } },
    { "desert/villagers/unemployed", { 1,3,1 } },
    { "desert/zombie/houses/desert_medium_house_1", { 6,6,7 } },
    { "desert/zombie/houses/desert_medium_house_2", { 11,9,7 } },
    { "desert/zombie/houses/desert_small_house_1", { 6,6,5 } },
    { "desert/zombie/houses/desert_small_house_2", { 7,6,5 } },
    { "desert/zombie/houses/desert_small_house_3", { 5,5,6 } },
    { "desert/zombie/houses/desert_small_house_4", { 5,5,5 } },
    { "desert/zombie/houses/desert_small_house_5", { 5,6,6 } },
    { "desert/zombie/houses/desert_small_house_6", { 5,17,5 } },
    { "desert/zombie/houses/desert_small_house_7", { 8,5,7 } },
    { "desert/zombie/houses/desert_small_house_8", { 5,5,5 } },
    { "desert/zombie/streets/corner_01", { 7,2,15 } },
    { "desert/zombie/streets/corner_02", { 6,2,6 } },
    { "desert/zombie/streets/crossroad_01", { 18,2,15 } },
    { "desert/zombie/streets/crossroad_02", { 11,2,11 } },
    { "desert/zombie/streets/crossroad_03", { 5,2,5 } },
    { "desert/zombie/streets/square_01", { 13,2,28 } },
    { "desert/zombie/streets/square_02", { 16,2,19 } },
    { "desert/zombie/streets/straight_01", { 15,2,12 } },
    { "desert/zombie/streets/straight_02", { 15,2,18 } },
    { "desert/zombie/streets/straight_03", { 4,2,3 } },
    { "desert/zombie/streets/turn_01", { 4,2,4 } },
    { "desert/zombie/terminators/terminator_02", { 3,2,3 } },
    { "desert/zombie/town_centers/desert_meeting_point_1", { 17,6,9 } },
    { "desert/zombie/town_centers/desert_meeting_point_2", { 12,6,12 } },
    { "desert/zombie/town_centers/desert_meeting_point_3", { 15,6,15 } },
    { "desert/zombie/villagers/nitwit", { 1,3,1 } },
    { "desert/zombie/villagers/unemployed", { 1,3,1 } },
    { "plains/plains_lamp_1", { 3,4,3 } },
    { "plains/houses/plains_accessory_1", { 3,2,5 } },
    { "plains/houses/plains_animal_pen_1", { 5,8,6 } },
    { "plains/houses/plains_animal_pen_2", { 7,7,11 } },
    { "plains/houses/plains_animal_pen_3", { 8,6,11 } },
    { "plains/houses/plains_armorer_house_1", { 9,8,8 } },
    { "plains/houses/plains_big_house_1", { 7,11,11 } },
    { "plains/houses/plains_butcher_shop_1", { 11,8,12 } },
    { "plains/houses/plains_butcher_shop_2", { 15,12,7 } },
    { "plains/houses/plains_cartographer_1", { 10,8,7 } },
    { "plains/houses/plains_fisher_cottage_1", { 11,9,10 } },
    { "plains/houses/plains_fletcher_house_1", { 9,7,11 } },
    { "plains/houses/plains_large_farm_1", { 13,6,9 } },
    { "plains/houses/plains_library_1", { 11,10,17 } },
    { "plains/houses/plains_library_2", { 8,10,9 } },
    { "plains/houses/plains_masons_house_1", { 8,7,9 } },
    { "plains/houses/plains_medium_house_1", { 13,8,11 } },
    { "plains/houses/plains_medium_house_2", { 7,6,13 } },
    { "plains/houses/plains_meeting_point_4", { 10,7,16 } },
    { "plains/houses/plains_meeting_point_5", { 10,6,11 } },
    { "plains/houses/plains_shepherds_house_1", { 9,6,13 } },
    { "plains/houses/plains_small_farm_1", { 7,6,9 } },
    { "plains/houses/plains_small_house_1", { 7,7,7 } },
    { "plains/houses/plains_small_house_2", { 7,7,7 } },
    { "plains/houses/plains_small_house_3", { 7,7,7 } },
    { "plains/houses/plains_small_house_4", { 7,7,7 } },
    { "plains/houses/plains_small_house_5", { 9,11,9 } },
    { "plains/houses/plains_small_house_6", { 7,7,7 } },
    { "plains/houses/plains_small_house_7", { 7,7,8 } },
    { "plains/houses/plains_small_house_8", { 8,9,9 } },
    { "plains/houses/plains_stable_1", { 9,7,16 } },
    { "plains/houses/plains_stable_2", { 7,6,17 } },
    { "plains/houses/plains_tannery_1", { 8,7,10 } },
    { "plains/houses/plains_temple_3", { 11,7,7 } },
    { "plains/houses/plains_temple_4", { 10,12,7 } },
    { "plains/houses/plains_tool_smith_1", { 9,6,12 } },
    { "plains/houses/plains_weaponsmith_1", { 9,8,11 } },
    { "plains/streets/corner_01", { 16,2,16 } },
    { "plains/streets/corner_02", { 16,2,16 } },
    { "plains/streets/corner_03", { 4,2,4 } },
    { "plains/streets/crossroad_01", { 16,2,16 } },
    { "plains/streets/crossroad_02", { 16,2,16 } },
    { "plains/streets/crossroad_03", { 16,2,16 } },
    { "plains/streets/crossroad_04", { 4,2,5 } },
    { "plains/streets/crossroad_05", { 5,2,5 } },
    { "plains/streets/crossroad_06", { 5,2,5 } },
    { "plains/streets/straight_01", { 16,2,16 } },
    { "plains/streets/straight_02", { 16,2,16 } },
    { "plains/streets/straight_03", { 13,2,11 } },
    { "plains/streets/straight_04", { 11,2,9 } },
    { "plains/streets/straight_05", { 20,2,17 } },
    { "plains/streets/straight_06", { 21,2,18 } },
    { "plains/streets/turn_01", { 18,2,8 } },
    { "plains/terminators/terminator_01", { 2,2,3 } },
    { "plains/terminators/terminator_02", { 1,2,1 } },
    { "plains/terminators/terminator_03", { 3,2,3 } },
    { "plains/terminators/terminator_04", { 4,2,4 } },
    { "plains/town_centers/plains_fountain_01", { 9,4,9 } },
    { "plains/town_centers/plains_meeting_point_1", { 10,7,10 } },
    { "plains/town_centers/plains_meeting_point_2", { 8,5,15 } },
    { "plains/town_centers/plains_meeting_point_3", { 11,9,11 } },
    { "plains/villagers/baby", { 1,2,1 } },
    { "plains/villagers/nitwit", { 1,3,1 } },
    { "plains/villagers/unemployed", { 1,3,1 } },
    { "plains/zombie/houses/plains_animal_pen_3", { 8,6,11 } },
    { "plains/zombie/houses/plains_big_house_1", { 7,11,11 } },
    { "plains/zombie/houses/plains_butcher_shop_2", { 15,12,7 } },
    { "plains/zombie/houses/plains_fletcher_house_1", { 9,7,11 } },
    { "plains/zombie/houses/plains_medium_house_1", { 13,8,11 } },
    { "plains/zombie/houses/plains_medium_house_2", { 7,6,13 } },
    { "plains/zombie/houses/plains_meeting_point_4", { 10,7,16 } },
    { "plains/zombie/houses/plains_meeting_point_5", { 10,6,11 } },
    { "plains/zombie/houses/plains_shepherds_house_1", { 9,6,13 } },
    { "plains/zombie/houses/plains_small_house_1", { 7,7,7 } },
    { "plains/zombie/houses/plains_small_house_2", { 7,7,7 } },
    { "plains/zombie/houses/plains_small_house_3", { 7,7,7 } },
    { "plains/zombie/houses/plains_small_house_4", { 7,7,7 } },
    { "plains/zombie/houses/plains_small_house_5", { 9,11,9 } },
    { "plains/zombie/houses/plains_small_house_6", { 7,7,7 } },
    { "plains/zombie/houses/plains_small_house_7", { 7,7,8 } },
    { "plains/zombie/houses/plains_small_house_8", { 8,9,9 } },
    { "plains/zombie/houses/plains_stable_1", { 9,7,16 } },
    { "plains/zombie/streets/corner_01", { 16,2,16 } },
    { "plains/zombie/streets/corner_02", { 16,2,16 } },
    { "plains/zombie/streets/corner_03", { 4,2,4 } },
    { "plains/zombie/streets/crossroad_01", { 16,2,16 } },
    { "plains/zombie/streets/crossroad_02", { 16,2,16 } },
    { "plains/zombie/streets/crossroad_03", { 16,2,16 } },
    { "plains/zombie/streets/crossroad_04", { 4,2,5 } },
    { "plains/zombie/streets/crossroad_05", { 5,2,5 } },
    { "plains/zombie/streets/crossroad_06", { 5,2,5 } },
    { "plains/zombie/streets/straight_01", { 16,2,16 } },
    { "plains/zombie/streets/straight_02", { 16,2,16 } },
    { "plains/zombie/streets/straight_03", { 13,2,11 } },
    { "plains/zombie/streets/straight_04", { 11,2,9 } },
    { "plains/zombie/streets/straight_05", { 20,2,17 } },
    { "plains/zombie/streets/straight_06", { 21,2,18 } },
    { "plains/zombie/streets/turn_01", { 18,2,8 } },
    { "plains/zombie/town_centers/plains_fountain_01", { 9,6,9 } },
    { "plains/zombie/town_centers/plains_meeting_point_1", { 10,7,10 } },
    { "plains/zombie/town_centers/plains_meeting_point_2", { 8,5,15 } },
    { "plains/zombie/town_centers/plains_meeting_point_3", { 11,9,11 } },
    { "plains/zombie/villagers/nitwit", { 1,3,1 } },
    { "plains/zombie/villagers/unemployed", { 1,3,1 } },
    { "savanna/savanna_lamp_post_01", { 1,2,1 } },
    { "savanna/houses/savanna_animal_pen_1", { 9,5,9 } },
    { "savanna/houses/savanna_animal_pen_2", { 13,7,12 } },
    { "savanna/houses/savanna_animal_pen_3", { 8,5,9 } },
    { "savanna/houses/savanna_armorer_1", { 7,7,7 } },
    { "savanna/houses/savanna_butchers_shop_1", { 11,8,11 } },
    { "savanna/houses/savanna_butchers_shop_2", { 13,10,9 } },
    { "savanna/houses/savanna_cartographer_1", { 8,8,9 } },
    { "savanna/houses/savanna_fisher_cottage_1", { 8,11,9 } },
    { "savanna/houses/savanna_fletcher_house_1", { 11,7,9 } },
    { "savanna/houses/savanna_large_farm_1", { 9,6,9 } },
    { "savanna/houses/savanna_large_farm_2", { 10,7,8 } },
    { "savanna/houses/savanna_library_1", { 10,8,8 } },
    { "savanna/houses/savanna_mason_1", { 8,7,10 } },
    { "savanna/houses/savanna_medium_house_1", { 8,7,15 } },
    { "savanna/houses/savanna_medium_house_2", { 10,8,11 } },
    { "savanna/houses/savanna_shepherd_1", { 13,14,11 } },
    { "savanna/houses/savanna_small_farm", { 6,7,9 } },
    { "savanna/houses/savanna_small_house_1", { 7,7,7 } },
    { "savanna/houses/savanna_small_house_2", { 7,7,7 } },
    { "savanna/houses/savanna_small_house_3", { 7,7,7 } },
    { "savanna/houses/savanna_small_house_4", { 10,8,7 } },
    { "savanna/houses/savanna_small_house_5", { 7,10,7 } },
    { "savanna/houses/savanna_small_house_6", { 7,7,7 } },
    { "savanna/houses/savanna_small_house_7", { 7,7,7 } },
    { "savanna/houses/savanna_small_house_8", { 6,7,7 } },
    { "savanna/houses/savanna_tannery_1", { 8,6,9 } },
    { "savanna/houses/savanna_temple_1", { 13,8,9 } },
    { "savanna/houses/savanna_temple_2", { 7,7,9 } },
    { "savanna/houses/savanna_tool_smith_1", { 7,7,11 } },
    { "savanna/houses/savanna_weaponsmith_1", { 8,6,9 } },
    { "savanna/houses/savanna_weaponsmith_2", { 9,7,13 } },
    { "savanna/streets/corner_01", { 16,2,16 } },
    { "savanna/streets/corner_03", { 4,2,4 } },
    { "savanna/streets/crossroad_02", { 7,2,10 } },
    { "savanna/streets/crossroad_03", { 16,2,16 } },
    { "savanna/streets/crossroad_04", { 4,2,5 } },
    { "savanna/streets/crossroad_05", { 5,2,5 } },
    { "savanna/streets/crossroad_06", { 5,2,5 } },
    { "savanna/streets/crossroad_07", { 15,2,14 } },
    { "savanna/streets/split_01", { 8,2,6 } },
    { "savanna/streets/split_02", { 14,2,9 } },
    { "savanna/streets/straight_02", { 16,2,16 } },
    { "savanna/streets/straight_04", { 11,2,9 } },
    { "savanna/streets/straight_05", { 20,2,17 } },
    { "savanna/streets/straight_06", { 9,2,14 } },
    { "savanna/streets/straight_08", { 10,2,16 } },
    { "savanna/streets/straight_09", { 23,2,16 } },
    { "savanna/streets/straight_10", { 6,2,11 } },
    { "savanna/streets/straight_11", { 17,2,17 } },
    { "savanna/streets/turn_01", { 19,2,11 } },
    { "savanna/terminators/terminator_05", { 16,2,16 } },
    { "savanna/town_centers/savanna_meeting_point_1", { 14,5,12 } },
    { "savanna/town_centers/savanna_meeting_point_2", { 11,6,11 } },
    { "savanna/town_centers/savanna_meeting_point_3", { 9,6,11 } },
    { "savanna/town_centers/savanna_meeting_point_4", { 9,6,9 } },
    { "savanna/villagers/baby", { 1,2,1 } },
    { "savanna/villagers/nitwit", { 1,3,1 } },
    { "savanna/villagers/unemployed", { 1,3,1 } },
    { "savanna/zombie/houses/savanna_animal_pen_2", { 13,7,12 } },
    { "savanna/zombie/houses/savanna_animal_pen_3", { 8,5,9 } },
    { "savanna/zombie/houses/savanna_large_farm_2", { 10,7,8 } },
    { "savanna/zombie/houses/savanna_medium_house_1", { 8,7,15 } },
    { "savanna/zombie/houses/savanna_medium_house_2", { 10,8,11 } },
    { "savanna/zombie/houses/savanna_small_house_1", { 7,7,7 } },
    { "savanna/zombie/houses/savanna_small_house_2", { 7,7,7 } },
    { "savanna/zombie/houses/savanna_small_house_3", { 7,7,7 } },
    { "savanna/zombie/houses/savanna_small_house_4", { 10,8,7 } },
    { "savanna/zombie/houses/savanna_small_house_5", { 7,10,7 } },
    { "savanna/zombie/houses/savanna_small_house_6", { 7,7,7 } },
    { "savanna/zombie/houses/savanna_small_house_7", { 7,7,7 } },
    { "savanna/zombie/houses/savanna_small_house_8", { 6,7,7 } },
    { "savanna/zombie/streets/corner_01", { 16,2,16 } },
    { "savanna/zombie/streets/corner_03", { 4,2,4 } },
    { "savanna/zombie/streets/crossroad_02", { 7,2,10 } },
    { "savanna/zombie/streets/crossroad_03", { 16,2,16 } },
    { "savanna/zombie/streets/crossroad_04", { 4,2,5 } },
    { "savanna/zombie/streets/crossroad_05", { 5,2,5 } },
    { "savanna/zombie/streets/crossroad_06", { 5,2,5 } },
    { "savanna/zombie/streets/crossroad_07", { 15,2,14 } },
    { "savanna/zombie/streets/split_01", { 8,2,6 } },
    { "savanna/zombie/streets/split_02", { 14,2,9 } },
    { "savanna/zombie/streets/straight_02", { 16,2,16 } },
    { "savanna/zombie/streets/straight_04", { 11,2,9 } },
    { "savanna/zombie/streets/straight_05", { 20,2,17 } },
    { "savanna/zombie/streets/straight_06", { 9,2,14 } },
    { "savanna/zombie/streets/straight_08", { 10,2,16 } },
    { "savanna/zombie/streets/straight_09", { 23,2,16 } },
    { "savanna/zombie/streets/straight_10", { 6,2,11 } },
    { "savanna/zombie/streets/straight_11", { 17,2,17 } },
    { "savanna/zombie/streets/turn_01", { 19,2,11 } },
    { "savanna/zombie/terminators/terminator_05", { 16,2,16 } },
    { "savanna/zombie/town_centers/savanna_meeting_point_1", { 14,6,12 } },
    { "savanna/zombie/town_centers/savanna_meeting_point_2", { 11,6,11 } },
    { "savanna/zombie/town_centers/savanna_meeting_point_3", { 9,6,11 } },
    { "savanna/zombie/town_centers/savanna_meeting_point_4", { 9,6,9 } },
    { "savanna/zombie/villagers/nitwit", { 1,3,1 } },
    { "savanna/zombie/villagers/unemployed", { 1,3,1 } },
    { "snowy/snowy_lamp_post_01", { 3,4,1 } },
    { "snowy/snowy_lamp_post_02", { 2,4,1 } },
    { "snowy/snowy_lamp_post_03", { 3,4,3 } },
    { "snowy/houses/snowy_animal_pen_1", { 8,6,9 } },
    { "snowy/houses/snowy_animal_pen_2", { 9,6,8 } },
    { "snowy/houses/snowy_armorer_house_1", { 8,8,7 } },
    { "snowy/houses/snowy_armorer_house_2", { 7,8,7 } },
    { "snowy/houses/snowy_butchers_shop_1", { 7,8,9 } },
    { "snowy/houses/snowy_butchers_shop_2", { 9,5,5 } },
    { "snowy/houses/snowy_cartographer_house_1", { 7,7,11 } },
    { "snowy/houses/snowy_farm_1", { 6,6,7 } },
    { "snowy/houses/snowy_farm_2", { 7,6,9 } },
    { "snowy/houses/snowy_fisher_cottage", { 9,8,7 } },
    { "snowy/houses/snowy_fletcher_house_1", { 9,8,7 } },
    { "snowy/houses/snowy_library_1", { 13,10,7 } },
    { "snowy/houses/snowy_masons_house_1", { 10,8,9 } },
    { "snowy/houses/snowy_masons_house_2", { 9,10,9 } },
    { "snowy/houses/snowy_medium_house_1", { 7,6,8 } },
    { "snowy/houses/snowy_medium_house_2", { 14,9,7 } },
    { "snowy/houses/snowy_medium_house_3", { 5,5,7 } },
    { "snowy/houses/snowy_shepherds_house_1", { 9,5,10 } },
    { "snowy/houses/snowy_small_house_1", { 7,5,6 } },
    { "snowy/houses/snowy_small_house_2", { 7,8,7 } },
    { "snowy/houses/snowy_small_house_3", { 7,6,7 } },
    { "snowy/houses/snowy_small_house_4", { 8,5,7 } },
    { "snowy/houses/snowy_small_house_5", { 7,5,5 } },
    { "snowy/houses/snowy_small_house_6", { 7,9,7 } },
    { "snowy/houses/snowy_small_house_7", { 6,7,7 } },
    { "snowy/houses/snowy_small_house_8", { 6,5,5 } },
    { "snowy/houses/snowy_tannery_1", { 8,9,9 } },
    { "snowy/houses/snowy_temple_1", { 10,14,7 } },
    { "snowy/houses/snowy_tool_smith_1", { 8,8,7 } },
    { "snowy/houses/snowy_weapon_smith_1", { 9,7,10 } },
    { "snowy/streets/corner_01", { 13,2,16 } },
    { "snowy/streets/corner_02", { 16,2,16 } },
    { "snowy/streets/corner_03", { 4,2,4 } },
    { "snowy/streets/crossroad_01", { 16,2,16 } },
    { "snowy/streets/crossroad_02", { 16,2,16 } },
    { "snowy/streets/crossroad_03", { 16,2,17 } },
    { "snowy/streets/crossroad_04", { 4,2,5 } },
    { "snowy/streets/crossroad_05", { 5,2,5 } },
    { "snowy/streets/crossroad_06", { 5,2,5 } },
    { "snowy/streets/square_01", { 20,2,17 } },
    { "snowy/streets/straight_01", { 16,2,16 } },
    { "snowy/streets/straight_02", { 16,2,16 } },
    { "snowy/streets/straight_03", { 13,2,11 } },
    { "snowy/streets/straight_04", { 11,2,9 } },
    { "snowy/streets/straight_06", { 21,2,18 } },
    { "snowy/streets/straight_08", { 16,2,17 } },
    { "snowy/streets/turn_01", { 18,2,8 } },
    { "snowy/town_centers/snowy_meeting_point_1", { 12,8,8 } },
    { "snowy/town_centers/snowy_meeting_point_2", { 11,5,9 } },
    { "snowy/town_centers/snowy_meeting_point_3", { 7,7,7 } },
    { "snowy/villagers/baby", { 1,2,1 } },
    { "snowy/villagers/nitwit", { 1,3,1 } },
    { "snowy/villagers/unemployed", { 1,3,1 } },
    { "snowy/zombie/houses/snowy_medium_house_1", { 7,6,8 } },
    { "snowy/zombie/houses/snowy_medium_house_2", { 14,9,7 } },
    { "snowy/zombie/houses/snowy_medium_house_3", { 5,5,7 } },
    { "snowy/zombie/houses/snowy_small_house_1", { 7,5,6 } },
    { "snowy/zombie/houses/snowy_small_house_2", { 7,8,7 } },
    { "snowy/zombie/houses/snowy_small_house_3", { 7,6,7 } },
    { "snowy/zombie/houses/snowy_small_house_4", { 8,5,7 } },
    { "snowy/zombie/houses/snowy_small_house_5", { 7,5,5 } },
    { "snowy/zombie/houses/snowy_small_house_6", { 7,9,7 } },
    { "snowy/zombie/houses/snowy_small_house_7", { 6,7,7 } },
    { "snowy/zombie/houses/snowy_small_house_8", { 6,4,5 } },
    { "snowy/zombie/streets/corner_01", { 13,2,16 } },
    { "snowy/zombie/streets/corner_02", { 16,2,16 } },
    { "snowy/zombie/streets/corner_03", { 4,2,4 } },
    { "snowy/zombie/streets/crossroad_01", { 16,2,16 } },
    { "snowy/zombie/streets/crossroad_02", { 16,2,16 } },
    { "snowy/zombie/streets/crossroad_03", { 16,2,17 } },
    { "snowy/zombie/streets/crossroad_04", { 4,2,5 } },
    { "snowy/zombie/streets/crossroad_05", { 5,2,5 } },
    { "snowy/zombie/streets/crossroad_06", { 5,2,5 } },
    { "snowy/zombie/streets/square_01", { 20,2,17 } },
    { "snowy/zombie/streets/straight_01", { 16,2,16 } },
    { "snowy/zombie/streets/straight_02", { 16,2,16 } },
    { "snowy/zombie/streets/straight_03", { 13,2,11 } },
    { "snowy/zombie/streets/straight_04", { 11,2,9 } },
    { "snowy/zombie/streets/straight_06", { 21,2,18 } },
    { "snowy/zombie/streets/straight_08", { 16,2,17 } },
    { "snowy/zombie/streets/turn_01", { 18,2,8 } },
    { "snowy/zombie/town_centers/snowy_meeting_point_1", { 12,8,8 } },
    { "snowy/zombie/town_centers/snowy_meeting_point_2", { 11,6,9 } },
    { "snowy/zombie/town_centers/snowy_meeting_point_3", { 7,7,7 } },
    { "snowy/zombie/villagers/nitwit", { 1,3,1 } },
    { "snowy/zombie/villagers/unemployed", { 1,3,1 } },
    { "taiga/taiga_decoration_1", { 3,2,6 } },
    { "taiga/taiga_decoration_2", { 2,2,3 } },
    { "taiga/taiga_decoration_3", { 1,2,2 } },
    { "taiga/taiga_decoration_4", { 1,2,2 } },
    { "taiga/taiga_decoration_5", { 1,1,1 } },
    { "taiga/taiga_decoration_6", { 3,2,3 } },
    { "taiga/taiga_lamp_post_1", { 1,2,1 } },
    { "taiga/houses/taiga_animal_pen_1", { 13,5,8 } },
    { "taiga/houses/taiga_armorer_2", { 7,8,7 } },
    { "taiga/houses/taiga_armorer_house_1", { 10,7,7 } },
    { "taiga/houses/taiga_butcher_shop_1", { 11,7,9 } },
    { "taiga/houses/taiga_cartographer_house_1", { 7,10,8 } },
    { "taiga/houses/taiga_fisher_cottage_1", { 10,8,12 } },
    { "taiga/houses/taiga_fletcher_house_1", { 10,6,11 } },
    { "taiga/houses/taiga_large_farm_1", { 10,7,10 } },
    { "taiga/houses/taiga_large_farm_2", { 8,7,9 } },
    { "taiga/houses/taiga_library_1", { 11,10,8 } },
    { "taiga/houses/taiga_masons_house_1", { 8,7,9 } },
    { "taiga/houses/taiga_medium_house_1", { 8,11,7 } },
    { "taiga/houses/taiga_medium_house_2", { 7,11,8 } },
    { "taiga/houses/taiga_medium_house_3", { 8,7,13 } },
    { "taiga/houses/taiga_medium_house_4", { 9,7,9 } },
    { "taiga/houses/taiga_shepherds_house_1", { 10,7,11 } },
    { "taiga/houses/taiga_small_farm_1", { 7,7,8 } },
    { "taiga/houses/taiga_small_house_1", { 7,8,9 } },
    { "taiga/houses/taiga_small_house_2", { 7,7,7 } },
    { "taiga/houses/taiga_small_house_3", { 7,7,7 } },
    { "taiga/houses/taiga_small_house_4", { 7,6,8 } },
    { "taiga/houses/taiga_small_house_5", { 9,7,7 } },
    { "taiga/houses/taiga_tannery_1", { 9,6,9 } },
    { "taiga/houses/taiga_temple_1", { 13,14,11 } },
    { "taiga/houses/taiga_tool_smith_1", { 11,6,8 } },
    { "taiga/houses/taiga_weaponsmith_1", { 7,9,7 } },
    { "taiga/houses/taiga_weaponsmith_2", { 6,5,7 } },
    { "taiga/streets/corner_01", { 16,2,16 } },
    { "taiga/streets/corner_02", { 16,2,16 } },
    { "taiga/streets/corner_03", { 4,2,4 } },
    { "taiga/streets/crossroad_01", { 16,2,16 } },
    { "taiga/streets/crossroad_02", { 16,2,16 } },
    { "taiga/streets/crossroad_03", { 16,2,16 } },
    { "taiga/streets/crossroad_04", { 4,2,5 } },
    { "taiga/streets/crossroad_05", { 5,2,5 } },
    { "taiga/streets/crossroad_06", { 5,2,5 } },
    { "taiga/streets/straight_01", { 16,2,16 } },
    { "taiga/streets/straight_02", { 16,2,16 } },
    { "taiga/streets/straight_03", { 13,2,11 } },
    { "taiga/streets/straight_04", { 11,2,9 } },
    { "taiga/streets/straight_05", { 20,2,17 } },
    { "taiga/streets/straight_06", { 21,2,18 } },
    { "taiga/streets/turn_01", { 18,2,8 } },
    { "taiga/town_centers/taiga_meeting_point_1", { 22,3,18 } },
    { "taiga/town_centers/taiga_meeting_point_2", { 9,7,9 } },
    { "taiga/villagers/baby", { 1,2,1 } },
    { "taiga/villagers/nitwit", { 1,3,1 } },
    { "taiga/villagers/unemployed", { 1,3,1 } },
    { "taiga/zombie/houses/taiga_cartographer_house_1", { 7,10,8 } },
    { "taiga/zombie/houses/taiga_fisher_cottage_1", { 10,8,12 } },
    { "taiga/zombie/houses/taiga_large_farm_2", { 8,7,9 } },
    { "taiga/zombie/houses/taiga_library_1", { 11,10,8 } },
    { "taiga/zombie/houses/taiga_medium_house_1", { 8,11,7 } },
    { "taiga/zombie/houses/taiga_medium_house_2", { 7,11,8 } },
    { "taiga/zombie/houses/taiga_medium_house_3", { 8,7,13 } },
    { "taiga/zombie/houses/taiga_medium_house_4", { 9,7,9 } },
    { "taiga/zombie/houses/taiga_shepherds_house_1", { 10,7,11 } },
    { "taiga/zombie/houses/taiga_small_house_1", { 7,8,9 } },
    { "taiga/zombie/houses/taiga_small_house_2", { 7,7,7 } },
    { "taiga/zombie/houses/taiga_small_house_3", { 7,7,7 } },
    { "taiga/zombie/houses/taiga_small_house_4", { 7,6,8 } },
    { "taiga/zombie/houses/taiga_small_house_5", { 9,7,7 } },
    { "taiga/zombie/houses/taiga_temple_1", { 13,14,11 } },
    { "taiga/zombie/houses/taiga_tool_smith_1", { 11,6,8 } },
    { "taiga/zombie/houses/taiga_weaponsmith_2", { 6,5,7 } },
    { "taiga/zombie/streets/corner_01", { 16,2,16 } },
    { "taiga/zombie/streets/corner_02", { 16,2,16 } },
    { "taiga/zombie/streets/corner_03", { 4,2,4 } },
    { "taiga/zombie/streets/crossroad_01", { 16,2,16 } },
    { "taiga/zombie/streets/crossroad_02", { 16,2,16 } },
    { "taiga/zombie/streets/crossroad_03", { 16,2,16 } },
    { "taiga/zombie/streets/crossroad_04", { 4,2,5 } },
    { "taiga/zombie/streets/crossroad_05", { 5,2,5 } },
    { "taiga/zombie/streets/crossroad_06", { 5,2,5 } },
    { "taiga/zombie/streets/straight_01", { 16,2,16 } },
    { "taiga/zombie/streets/straight_02", { 16,2,16 } },
    { "taiga/zombie/streets/straight_03", { 13,2,11 } },
    { "taiga/zombie/streets/straight_04", { 11,2,9 } },
    { "taiga/zombie/streets/straight_05", { 20,2,17 } },
    { "taiga/zombie/streets/straight_06", { 21,2,18 } },
    { "taiga/zombie/streets/turn_01", { 18,2,8 } },
    { "taiga/zombie/town_centers/taiga_meeting_point_1", { 22,6,18 } },
    { "taiga/zombie/town_centers/taiga_meeting_point_2", { 9,7,9 } },
    { "taiga/zombie/villagers/nitwit", { 1,3,1 } },
    { "taiga/zombie/villagers/unemployed", { 1,3,1 } },
};
#define N_ENTRIES  (int)(sizeof(STRUCTURE_SIZE)/sizeof(STRUCTURE_SIZE[0]))
/* --- Hash table en open-addressing, taille = pow2 >= 2*N (LF ~0.5) --- */
static constexpr uint32_t next_pow2_u32(uint32_t v){
    if (v <= 1) return 1;
    v--;
    v |= v >> 1;
    v |= v >> 2;
    v |= v >> 4;
    v |= v >> 8;
    v |= v >> 16;
    return v + 1;
}
#define LOAD_FACTOR_NUM 1
#define LOAD_FACTOR_DEN 2
enum { HT_SIZE = (int)next_pow2_u32((N_ENTRIES * LOAD_FACTOR_DEN) / LOAD_FACTOR_NUM) };

/* Slots stockent l'index dans ENTRIES, -1 = vide */
static int32_t HT_INDEX[HT_SIZE];

/* FNV-1a 64 -> 32 (rapide & bonne distrib) */
static inline uint32_t fnv1a32(const char *s){
    uint64_t h = 1469598103934665603ull;
    while (*s){
        h ^= (unsigned char)*s++;
        h *= 1099511628211ull;
    }
    /* réduire en 32 bits (xor-folding) */
    return (uint32_t)(h ^ (h >> 32));
}

static bool ht_build(void){
    for (int i=0;i<HT_SIZE;i++) HT_INDEX[i] = -1;
    for (int i=0;i<N_ENTRIES;i++){
        const char *k = STRUCTURE_SIZE[i].key;
        uint32_t h = fnv1a32(k);
        uint32_t mask = (uint32_t)(HT_SIZE - 1);
        uint32_t idx = h & mask;
        /* probing linéaire */
        while (HT_INDEX[idx] != -1){
            idx = (idx + 1) & mask;
        }
        HT_INDEX[idx] = i;
    }
    return true;
}

/* L'ancien drapeau `static int inited` n'était pas atomique : deux threads
 * appelant get_bpos() simultanément au démarrage pouvaient construire la table
 * en même temps. Une statique locale de fonction est initialisée exactement une
 * fois, les autres threads attendant, garanti par le standard depuis C++11. */
static inline void ht_init_once(void){
    static const bool built = ht_build();
    (void)built;
}

bool get_bpos(const char *key, BPos *out){
    ht_init_once();
    uint32_t h   = fnv1a32(key);
    uint32_t mask= (uint32_t)(HT_SIZE - 1);
    uint32_t idx = h & mask;

    /* parcourt jusqu'à un slot vide -> absent */
    for (int probes = 0; probes < HT_SIZE; ++probes){
        int32_t eidx = HT_INDEX[idx];
        if (eidx == -1) return false;                // slot vide => clé absente
        const Entry *e = &STRUCTURE_SIZE[eidx];
        /* comparaison courte: 1er char, puis strcmp */
        if (e->key[0] == key[0] && strcmp(e->key, key) == 0){
            if (out) *out = e->value;
            return true;
        }
        idx = (idx + 1) & mask;
    }
    return false; // table pleine (ne devrait pas arriver)
}